"""Add public_id for user table.

Revision ID: 1dcbc7c6221c
Revises: 2a1b1efca8ab
Create Date: 2026-08-11 20:35:15.603712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1dcbc7c6221c"
down_revision: str | Sequence[str] | None = "2a1b1efca8ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("public_id", sa.UUID(), nullable=False))
    op.create_unique_constraint("unique_public_id", "user", ["public_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_public_id", "user", type_="unique")
    op.drop_column("user", "public_id")
    # ### end Alembic commands ###
