"""Create task table.

Revision ID: 46afb1ecbeaf
Revises: 81c9d10341b6
Create Date: 2026-10-01 20:04:32.376986

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "46afb1ecbeaf"
down_revision: str | Sequence[str] | None = "81c9d10341b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hrid", sa.String(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("viewed_at", sa.DateTime(), nullable=True),
        sa.Column("recently_viewed_at", sa.DateTime(), nullable=True),
        sa.Column("solved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_unique_hrid", "task", ["hrid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_unique_hrid", table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
