"""Add status_update trigger for invitation.

Revision ID: f6efc47d34b5
Revises: 44d14b3a95be
Create Date: 2026-09-18 18:59:34.789132

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f6efc47d34b5"
down_revision: str | Sequence[str] | None = "44d14b3a95be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE OR REPLACE FUNCTION update_status_update_date()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.status_update_date := NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_invitation_update_date
        BEFORE UPDATE ON invitation
        FOR EACH ROW
        EXECUTE FUNCTION update_status_update_date();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP TRIGGER IF EXISTS trg_invitation_update_date ON invitation;
    """)

    op.execute("""
        DROP FUNCTION IF EXISTS update_status_update_date();
    """)
    # ### end Alembic commands ###
