"""Add type and subtype for game table.

Revision ID: 9316350eef71
Revises: 9e163704d47a
Create Date: 2026-08-28 20:24:55.444114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9316350eef71"
down_revision: str | Sequence[str] | None = "9e163704d47a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("type", sa.String(), nullable=False))
    op.add_column("game", sa.Column("subtype", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "subtype")
    op.drop_column("game", "type")
    # ### end Alembic commands ###
