"""Add modified_at for game table.

Revision ID: 3ab25bf919af
Revises: 9316350eef71
Create Date: 2026-08-29 10:05:06.882814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3ab25bf919af"
down_revision: str | Sequence[str] | None = "9316350eef71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game", sa.Column("modified_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "modified_at")
    # ### end Alembic commands ###
