"""FK added.

Revision ID: b3f79a1352d8
Revises: 7c9ae1021e92
Create Date: 2026-10-04 12:00:04.325648

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b3f79a1352d8"
down_revision: str | Sequence[str] | None = "7c9ae1021e92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_game_creator_user",
        "game",
        "user",
        ["creator"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_task_gameid_game",
        "task",
        "game",
        ["game_id"],
        ["public_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_task_assigneeid_user",
        "task",
        "user",
        ["assignee_id"],
        ["public_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_task_assigneeid_user", "task", type_="foreignkey")
    op.drop_constraint("fk_task_gameid_game", "task", type_="foreignkey")
    op.drop_constraint("fk_game_creator_user", "game", type_="foreignkey")
    # ### end Alembic commands ###
