"""Add network_edge table.

Revision ID: af24f9108cb4
Revises: 3ab25bf919af
Create Date: 2026-09-13 21:47:36.903721

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "af24f9108cb4"
down_revision: str | Sequence[str] | None = "3ab25bf919af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

role_enum = postgresql.ENUM(
    name="role",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "network_edge",
        sa.Column("user_one_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_one_role",
            role_enum,
            nullable=False,
        ),
        sa.Column("user_two_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_two_role",
            role_enum,
            nullable=False,
        ),
        sa.CheckConstraint("user_one_id < user_two_id", name="ck_ordered_id"),
        sa.PrimaryKeyConstraint(
            "user_one_id", "user_two_id", name="pk_network_edge"
        ),
    )
    op.create_index(
        "ix_edge_id_one", "network_edge", ["user_one_id"], unique=False
    )
    op.create_index(
        "ix_edge_id_two", "network_edge", ["user_two_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_edge_id_two", table_name="network_edge")
    op.drop_index("ix_edge_id_one", table_name="network_edge")
    op.drop_table("network_edge")
    # ### end Alembic commands ###
