"""Add index on user and title for game table.

Revision ID: 9e163704d47a
Revises: 7c351ed894cd
Create Date: 2026-08-28 18:52:23.506567

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9e163704d47a"
down_revision: str | Sequence[str] | None = "7c351ed894cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_unique_user_title", "game", ["creator", "title"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_unique_user_title", table_name="game")
    # ### end Alembic commands ###
