"""Add composite key receiver_id,status on invitation table.

Revision ID: d978d2f62f44
Revises: f6efc47d34b5
Create Date: 2026-09-20 16:19:31.907133

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d978d2f62f44"
down_revision: str | Sequence[str] | None = "f6efc47d34b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_receiver_status",
        "invitation",
        ["receiver_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_receiver_status", table_name="invitation")
    # ### end Alembic commands ###
