"""Add invitation table.

Revision ID: 44d14b3a95be
Revises: af24f9108cb4
Create Date: 2026-09-18 18:58:22.721728

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "44d14b3a95be"
down_revision: str | Sequence[str] | None = "af24f9108cb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

status_enum = sa.Enum(
    "ACCEPTED", "CANCELLED", "PENDING", "REJECTED", name="status"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("receiver_id", sa.UUID(), nullable=False),
        sa.Column("status", status_enum, nullable=False),
        sa.Column("send_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status_update_date", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "idx_invitation_public_id", "invitation", ["public_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_invitation_public_id", table_name="invitation")
    op.drop_table("invitation")
    # ### end Alembic commands ###
