"""Create user table.

Revision ID: 699405a859a9
Revises: ff86ff1cb39b
Create Date: 2026-05-31 20:54:34.782584

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "699405a859a9"
down_revision: str | Sequence[str] | None = "ff86ff1cb39b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

role_enum = sa.Enum("teacher", "student", name="role")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("role", role_enum, nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("idx_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("idx_user_username"), "user", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_user_username"), table_name="user")
    op.drop_index(op.f("idx_user_email"), table_name="user")
    op.drop_table("user")
    role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
