"""Replace roles columns with relation in network_edge table.

Revision ID: fe9b130f6963
Revises: d978d2f62f44
Create Date: 2026-09-26 15:00:13.477984

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "fe9b130f6963"
down_revision: str | Sequence[str] | None = "d978d2f62f44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

role_enum = postgresql.ENUM(name="role", create_type=False)
relation_enum = sa.Enum("teacher_student", "student_teacher", name="relation")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    relation_enum.create(op.get_bind(), checkfirst=True)
    op.drop_constraint(
        "pk_network_edge",
        "network_edge",
        type_="primary",
    )
    op.add_column(
        "network_edge", sa.Column("relation", relation_enum, nullable=False)
    )
    op.create_primary_key(
        "pk_network_edge",
        "network_edge",
        ["user_one_id", "user_two_id", "relation"],
    )
    op.drop_column("network_edge", "user_two_role")
    op.drop_column("network_edge", "user_one_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "network_edge",
        sa.Column(
            "user_one_role", role_enum, autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "network_edge",
        sa.Column(
            "user_two_role", role_enum, autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "pk_network_edge",
        "network_edge",
        type_="primary",
    )
    op.create_primary_key(
        "pk_network_edge",
        "network_edge",
        ["user_one_id", "user_two_id"],
    )
    op.drop_column("network_edge", "relation")
    relation_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
