"""Drop task table.

Revision ID: 81c9d10341b6
Revises: bd8f1262518d
Create Date: 2026-10-01 20:03:54.197326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "81c9d10341b6"
down_revision: str | Sequence[str] | None = "bd8f1262518d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_unique_hrid"), table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "assignee_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "viewed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "recently_viewed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("hrid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("task_pkey")),
    )
    op.create_index(op.f("idx_unique_hrid"), "task", ["hrid"], unique=True)
    # ### end Alembic commands ###
