"""Add game public_id.

Revision ID: 7c351ed894cd
Revises: 1dcbc7c6221c
Create Date: 2026-08-26 17:26:31.262066

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7c351ed894cd"
down_revision: str | Sequence[str] | None = "1dcbc7c6221c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("public_id", sa.UUID(), nullable=False))
    op.create_unique_constraint("game_public_id", "game", ["public_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("game_public_id", "game", type_="unique")
    op.drop_column("game", "public_id")
    # ### end Alembic commands ###
