"""Add human-readable id (hrid) for task table.

Revision ID: bd8f1262518d
Revises: fe9b130f6963
Create Date: 2026-09-30 19:55:02.395707

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bd8f1262518d"
down_revision: str | Sequence[str] | None = "fe9b130f6963"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("hrid", sa.String(), nullable=False))
    op.create_index("idx_unique_hrid", "task", ["hrid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_unique_hrid", table_name="task")
    op.drop_column("task", "hrid")
    # ### end Alembic commands ###
