class WordGamesError(Exception): ...


class ValidationError(WordGamesError): ...


class MissingDataError(ValidationError): ...


class TokenError(WordGamesError): ...


class SecurityViolationError(WordGamesError): ...
