name: CD

on:
  push:
    branches: [ main ]

env:
  UV_NO_SYNC: 1

jobs:
  build:
    name: Build (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]
    env:
      UV_NO_DEV: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Prevent dirty lockfile
        run: git diff --exit-code uv.lock

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync  --locked

      - name: Build package
        run: uv build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-py${{ matrix.python }}
          path: dist/
